In [1]:
import numpy as np
from Simulation import Simulation
import os

In [2]:
phase = np.loadtxt("../Case Analysis/data/phase")


In [3]:
z=np.ones_like(phase)*100
phase=phase*z

In [4]:
sim=Simulation(os.path.join(os.getcwd(),"..","vissim","aa","zhongsan.inp"),
               os.path.join(os.getcwd(),"..","vissim","aa","vissim.ini"))
# sim=Simulation("F:\\workspace\\jupyter\\论文\\graduation thesis\\vissim\\aa\\zhongsan.inp")

In [5]:
for i in range(sim.scs.Count):
    scs=sim.scs.GetSignalControllerByNumber(i+1).SignalGroups
    sim.Set_SignalGroups(scs,phase[i])

[  0.   28.2  28.2  61.2  61.2  61.2  85.9  85.9 100.  100. ]
[  0.   42.6  42.6  79.4  79.4  79.4  79.4 100.  100.  100. ]
[ 0.  18.7 18.7 38.7 47.7 47.7 73.7 73.7 99.7 99.7]
[  0.    0.   27.7  27.7  27.7  53.1  78.5  78.5 100.  100. ]
[  0.    0.   25.5  25.5  25.5  39.3  39.3  88.3  88.3 100. ]
[  0.   0.  65.  65.  65.  65.  65. 100. 100. 100.]
[  0.    0.   24.3  24.3  24.3  45.8  59.7  85.4 100.  100. ]
[  0.    0.   16.5  16.5  16.5  41.5  68.1  68.1 100.  100. ]
[  0.    0.   29.8  29.8  29.8  63.8  63.8 100.  100.  100. ]
[  0.    0.   37.9  37.9  37.9  71.6 100.  100.  100.  100. ]
[ 0.   0.  49.  49.  49.  72.1 85.3 85.3 99.6 99.6]
[  0.    0.   37.9  37.9  37.9  71.6  71.6  71.6 100.  100. ]
[ 0.   0.  30.  30.  30.  48.6 71.6 71.6 99.9 99.9]


In [22]:
import re
with open(os.path.join(os.getcwd(),"..","vissim","aa","zhongsan - 副本.inp")) as f:
    lines=f.read()
    fsch=re.finditer(r'TIMES +(\d+) *MEAN +(\d+.\d) +STANDARD_DEVIATION +(\d+.\d)',lines)
    for i in fsch:
        print(i.group(0))


TIMES 24   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES 23   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 22   MEAN 30.0  STANDARD_DEVIATION  0.0
TIMES 21   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 20   MEAN 30.0  STANDARD_DEVIATION  0.0
TIMES 19   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 18   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES 17   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 16   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES 15   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 14   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES 13   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 12   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES 11   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES 10   MEAN 30.0  STANDARD_DEVIATION  0.0
TIMES  9   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES  8   MEAN 30.0  STANDARD_DEVIATION  0.0
TIMES  7   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES  6   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES  5   MEAN 15.0  STANDARD_DEVIATION  0.0
TIMES  4   MEAN  0.0  STANDARD_DEVIATION  0.0
TIMES  3   MEAN 15.0  STANDARD_DEV

In [20]:
("%2.1f"%(1.2)).rjust(4," ")

' 1.2'